services:
  api:
    build:
      context: ../..
      dockerfile: entregable/Docker/Dockerfile
    container_name: gentera-api
    ports:
      - "8000:8000"
    environment:
      MODEL_PATH: /app/entregable/Salida/modelo_egreso_mejora.joblib
    volumes:
      - ../../Notebooks/Inputs:/app/data:ro
      - ../../artifacts:/app/artifacts
    restart: unless-stopped
